name: psasync

on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: PSA Copy

    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
      - name: gclone Run
        run: |
          rclone copy "gcl:/" "oned:/"  --stats=1s --stats-one-line -P --checkers=32 --transfers=5 --drive-pacer-min-sleep=1ms --drive-pacer-burst=1000
