name: psasyncgclone

on:
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: Gclone PSA Copy

    steps:
      - uses: actions/checkout@v2
      - name: rclone Install
        run: |
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone
      - name: rclone Config
        run: |
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.CONFIG_GCLONE }}
          EOF
      - name: gclone Install
        run: |
          wget https://github.com/donwa/gclone/releases/download/v1.51.0-mod1.3.1/gclone_1.51.0-mod1.3.1_Linux_x86_64.gz
          gzip -d gclone_1.51.0-mod1.3.1_Linux_x86_64.gz
          mv gclone_1.51.0-mod1.3.1_Linux_x86_64 gclone
          curl -L "${{ secrets.GCLONE_SA_DLURL }}" -o accounts.zip
          unzip accounts.zip
          rm accounts.zip
      - name: gclone Run
        run: |
          chmod +x gclone
          ./gclone copy "gcl:{0ADqjApvjJiOdUk9PVA}" "oned:/" -P --checkers=20 --transfers=5 --drive-pacer-min-sleep=1ms --drive-pacer-burst=1000
